### ISSUE TITLE
Can't start a diagram with yangster-app

### ISSUE THREAD

**Issue by hexa00** [theia-ide/yangster#55]
I get: 

[2018-02-02T12:10:41.311Z] ERROR: Theia/11950 on elxa4wqvvz1: 07:10:41 widget-0_sprotty Viewer: element not in DOM: [ 'widget-0_sprotty' ]

Ideas ?

**Comment by JanKoehnlein** [comment]
Just tried with a fresh yangster clone: 
- theia is not cloned (don't confuse it with theia-sprotty)
- it doesn't really pull latest (due to yarn being locked), but a pretty recent version of theia (0.3.2 from 10th of January).

We removed the submodule dependency on theia master in favor of an npm dependency to `@theia/latest` long time ago. Maybe your local repo clone has failed to cleanly reflect this. Adding/removing submodules is always a bit tricky.

I will upgrade the theia deps and fix the API issues. Then I'll try to get the [build against `next`](https://github.com/theia-ide/yangster/issues/52) working, such that we don't have to wait until after the theia release to adapt to API changes (and likely forget).

**Comment by JanKoehnlein** [comment]
Fixed with https://github.com/theia-ide/yangster/commit/6b0db391f2250c9871db62270ee524537fd8f69b

**Comment by hexa00** [comment]
Hi,
   Sorry I wasn't very clear in my issue I mean that doing from a fresh clone:

`cd yangster-app && yarn && yarn start`

Doesn't work, before I could not create a diagram and now I get:

```
index.js:45 Failed to start the frontend application.
index.js:47 Error: Cannot apply @injectable decorator multiple times.
    at injectable.js:8
    at DecorateConstructor (Reflect.ts:1202)
    at Object.decorate (Reflect.ts:742)
    at _decorate (decorator_utils.js:42)
    at Object.decorate (decorator_utils.js:55)
    at Object.defineProperty.value (widget.ts:13)
    at __webpack_require__ (bootstrap fe9a0c4…:659)
    at fn (bootstrap fe9a0c4…:85)
    at Object.__decorate (index.ts:8)
    at __webpack_require__ (bootstrap fe9a0c4…:659)
:3000/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

This is because yangster is out of date with theia as far as I can tell.

**Comment by hexa00** [comment]
Oops seems that package.json is using next now... 

Tested it with latest and it works now.
